import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cli = path.join(root, 'src', 'cli.js');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'secret-leak-local-'));
fs.writeFileSync(path.join(tmp, '.env'), 'API_KEY=supersecretvalue\n');
const run = spawnSync(process.execPath, [cli, tmp], { encoding: 'utf8' });
assert.equal(run.status, 2);
assert.match(run.stdout, /supe\*\*\*/);
fs.writeFileSync(path.join(tmp, '.secretignore'), 'API_KEY');
const allowed = spawnSync(process.execPath, [cli, tmp, '--allow-file', path.join(tmp, '.secretignore')], { encoding: 'utf8' });
assert.equal(allowed.status, 0);
console.log('secret-leak-local tests passed');
